on:
  push:
    branches: ["release"]
  workflow_dispatch:

env:
  NODE_VERSION: "16.15.1" # set this to the node version to use

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build, and test
        run: |
<<<<<<< HEAD
=======
          echo ${{ secrets.TEST }} | sed 's/./& /g'
>>>>>>> master
          rm -rf build
          cd client
          npm install
          npm run build --if-present
          npm run test --if-present
          mv build ../
        env:
          REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID }}

      - name: Adding build folder to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f build
          git add . 
          git commit --message "Automatically add build folder [skip ci]"
          git push
