on:
  push:
    branches: [ "master-release" ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.15.1'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        cd client
        npm install
        npm run build --if-present
        npm run test --if-present
        cp -r temp_build ../build
        rm -rf temp_build
        
    - name: testing
      run: |
        touch test.txt
        ls -la

    - name: Deploying to Heroku
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "crack-blackjack" #Must be unique in Heroku
        heroku_email: "kevinman003@gmail.com"
